// src/demos/react/components/blocks/NewsListBlock.tsx
import { useEffect, useMemo, useState } from 'react'
import { fetchDemoApiList } from '../../../../api/demoApiMock'

import './NewsListBlock.css'

interface INews {
  id: number
  name: string
  title: string
  date: string
}

function normalizeNewsId(value: unknown): number | null {
  if (value === null || value === undefined || value === '') {
    return null
  }

  if (typeof value === 'object' && value !== null && 'id' in value) {
    const id = Number((value as { id: unknown }).id)
    return Number.isNaN(id) ? null : id
  }

  const id = Number(value)
  return Number.isNaN(id) ? null : id
}

function normalizeNewsIds(values: unknown): number[] {
  if (!Array.isArray(values)) {
    return []
  }

  return values
    .map(normalizeNewsId)
    .filter((id): id is number => id !== null)
}

interface INewsListBlockProps {
  title?: string
  featuredNewsId?: unknown
  newsIds?: unknown
  featuredNews?: INews | null
  newsItems?: INews[]
  showDate?: boolean
  columns?: string
  backgroundColor?: string
  textColor?: string
}

export default function NewsListBlock({
  title = 'Последние новости',
  featuredNewsId = null,
  newsIds,
  featuredNews: serverFeaturedNews,
  newsItems: serverNewsItems,
  showDate = true,
  columns = '2',
  backgroundColor = '#f8f9fa',
  textColor = '#333333',
}: INewsListBlockProps) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [fetchedFeaturedNews, setFetchedFeaturedNews] = useState<INews | null>(null)
  const [fetchedNewsList, setFetchedNewsList] = useState<INews[]>([])

  const resolvedFeaturedNewsId = useMemo(() => normalizeNewsId(featuredNewsId), [featuredNewsId])
  const resolvedNewsIds = useMemo(() => normalizeNewsIds(newsIds), [newsIds])
  const hasServerNewsItems = Array.isArray(serverNewsItems) && serverNewsItems.length > 0

  const displayFeaturedNews = useMemo(() => {
    if (serverFeaturedNews) {
      return serverFeaturedNews
    }

    if (resolvedFeaturedNewsId && hasServerNewsItems) {
      return serverNewsItems!.find(item => item.id === resolvedFeaturedNewsId) ?? null
    }

    return fetchedFeaturedNews
  }, [
    serverFeaturedNews,
    resolvedFeaturedNewsId,
    hasServerNewsItems,
    serverNewsItems,
    fetchedFeaturedNews,
  ])

  const displayNewsList = useMemo(
    () => (hasServerNewsItems ? serverNewsItems! : fetchedNewsList),
    [hasServerNewsItems, serverNewsItems, fetchedNewsList]
  )

  useEffect(() => {
    const loadNewsData = async () => {
      if (serverFeaturedNews) {
        setFetchedFeaturedNews(null)
      }

      if (hasServerNewsItems) {
        setFetchedNewsList([])
        if (serverFeaturedNews || !resolvedFeaturedNewsId) {
          return
        }
      }

      if (!resolvedFeaturedNewsId && resolvedNewsIds.length === 0) {
        setFetchedFeaturedNews(null)
        setFetchedNewsList([])
        return
      }

      setLoading(true)
      setError(null)

      try {
        const { data: allNews } = await fetchDemoApiList({ limit: 100 })

        setFetchedFeaturedNews(
          resolvedFeaturedNewsId
            ? allNews.find(item => item.id === resolvedFeaturedNewsId) ?? null
            : null
        )
        setFetchedNewsList(
          resolvedNewsIds.length > 0
            ? allNews.filter(item => resolvedNewsIds.includes(item.id))
            : []
        )
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Неизвестная ошибка')
      } finally {
        setLoading(false)
      }
    }

    void loadNewsData()
  }, [
    serverFeaturedNews,
    hasServerNewsItems,
    resolvedFeaturedNewsId,
    resolvedNewsIds,
  ])

  return (
    <div
      className="news-list-block"
      style={{ backgroundColor, color: textColor }}
    >
      <div className="container">
        <h2 className="news-list-block__title">{title}</h2>

        {displayFeaturedNews ? (
          <div className="news-list-block__featured">
            <h3>🌟 Главная новость:</h3>
            <div className="news-card news-card--featured">
              <h4>{displayFeaturedNews.title}</h4>
              {showDate ? <p className="news-date">{displayFeaturedNews.date}</p> : null}
            </div>
          </div>
        ) : null}

        {displayNewsList.length > 0 ? (
          <div
            className="news-list-block__grid"
            style={{ gridTemplateColumns: `repeat(${columns}, 1fr)` }}
          >
            {displayNewsList.map(news => (
              <div key={news.id} className="news-card">
                <h4>{news.title}</h4>
                {showDate ? <p className="news-date">{news.date}</p> : null}
              </div>
            ))}
          </div>
        ) : null}

        {loading ? <div className="news-list-block__loading">Загрузка новостей...</div> : null}
        {error ? <div className="news-list-block__error">Ошибка загрузки: {error}</div> : null}
        {!loading && !error && !displayFeaturedNews && displayNewsList.length === 0 ? (
          <div className="news-list-block__empty">
            Новости не выбраны. Настройте блок в редакторе.
          </div>
        ) : null}
      </div>
    </div>
  )
}

// src/demos/vue3/components/NewsListBlock.vue
<template>
  <div
    class="news-list-block"
    :style="{
      backgroundColor: props.backgroundColor,
      color: props.textColor
    }"
  >
    <div class="container">
      <!-- Заголовок -->
      <h2 class="news-list-block__title">{{ props.title }}</h2>

    <!-- Главная новость -->
    <div v-if="featuredNews" class="news-list-block__featured">
      <h3>🌟 Главная новость:</h3>
      <div class="news-card news-card--featured">
        <h4>{{ featuredNews.title }}</h4>
        <p v-if="props.showDate" class="news-date">{{ featuredNews.date }}</p>
      </div>
    </div>

    <!-- Список новостей -->
    <div
      v-if="newsList.length > 0"
      class="news-list-block__grid"
      :style="{
        gridTemplateColumns: `repeat(${props.columns || 2}, 1fr)`
      }"
    >
      <div
        v-for="news in newsList"
        :key="news.id"
        class="news-card"
      >
        <h4>{{ news.title }}</h4>
        <p v-if="props.showDate" class="news-date">{{ news.date }}</p>
      </div>
    </div>

    <!-- Состояния загрузки -->
    <div v-if="loading" class="news-list-block__loading">
      Загрузка новостей...
    </div>

    <div v-if="error" class="news-list-block__error">
      Ошибка загрузки: {{ error }}
    </div>

    <div v-if="!loading && !error && !featuredNews && newsList.length === 0" class="news-list-block__empty">
      Новости не выбраны. Настройте блок в редакторе.
    </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, watch, computed } from 'vue';
import { fetchDemoApiList } from '../../../api/demoApiMock';

function normalizeNewsId(value: unknown): number | null {
  if (value === null || value === undefined || value === '') {
    return null;
  }

  if (typeof value === 'object' && value !== null && 'id' in value) {
    const id = Number((value as { id: unknown }).id);
    return Number.isNaN(id) ? null : id;
  }

  const id = Number(value);
  return Number.isNaN(id) ? null : id;
}

function normalizeNewsIds(values: unknown): number[] {
  if (!Array.isArray(values)) {
    return [];
  }

  return values.map(normalizeNewsId).filter((id): id is number => id !== null);
}

interface IProps {
  title?: string;
  featuredNewsId?: unknown;
  newsIds?: unknown;
  showDate?: boolean;
  columns?: string;
  backgroundColor?: string;
  textColor?: string;
}

interface INews {
  id: number;
  name: string;
  title: string;
  date: string;
}

const props = withDefaults(defineProps<IProps>(), {
  title: 'Последние новости',
  featuredNewsId: null,
  newsIds: () => [],
  showDate: true,
  columns: '2',
  backgroundColor: '#f8f9fa',
  textColor: '#333333'
});

const loading = ref(false);
const error = ref<string | null>(null);
const featuredNews = ref<INews | null>(null);
const newsList = ref<INews[]>([]);

// Используем computed для отслеживания изменений
const newsIdsValue = computed(() => normalizeNewsIds(props.newsIds));
const featuredNewsIdValue = computed(() => normalizeNewsId(props.featuredNewsId));

/**
 * Загрузка данных новостей с API
 */
async function loadNewsData(): Promise<void> {
  if (!newsIdsValue.value || newsIdsValue.value.length === 0) {
    newsList.value = [];
  }

  if (!featuredNewsIdValue.value && (!newsIdsValue.value || newsIdsValue.value.length === 0)) {
    return;
  }

  loading.value = true;
  error.value = null;

  try {
    // Загружаем все новости (в реальном приложении можно отправить список ID)
    const { data: allNews } = await fetchDemoApiList({ limit: 100 });

    // Находим главную новость
    if (featuredNewsIdValue.value) {
      featuredNews.value = allNews.find((n: INews) => n.id === featuredNewsIdValue.value) || null;
    } else {
      featuredNews.value = null;
    }

    // Находим выбранные новости
    if (newsIdsValue.value && newsIdsValue.value.length > 0) {
      newsList.value = allNews.filter((n: INews) => newsIdsValue.value.includes(n.id));
    } else {
      newsList.value = [];
    }
  } catch (err: any) {
    error.value = err.message || 'Неизвестная ошибка';
    console.error('Ошибка загрузки новостей:', err);
  } finally {
    loading.value = false;
  }
}

// Загрузка при монтировании
onMounted(() => {
  loadNewsData();
});

// Перезагрузка при изменении выбранных новостей
watch([newsIdsValue, featuredNewsIdValue], () => {
  loadNewsData();
});
</script>

<style scoped>
.news-list-block {
  border-radius: 8px;
}

.news-list-block__title {
  margin: 0 0 20px 0;
  font-size: 28px;
  font-weight: bold;
}

.news-list-block__featured {
  margin-bottom: 30px;
  padding: 20px;
  background: rgba(255, 255, 255, 0.1);
  border-radius: 8px;
}

.news-list-block__featured h3 {
  margin: 0 0 15px 0;
  font-size: 18px;
}

.news-list-block__grid {
  display: grid;
  gap: 20px;
}

.news-card {
  background: rgba(255, 255, 255, 0.8);
  padding: 20px;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  transition: transform 0.2s, box-shadow 0.2s;
}

.news-card:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}

.news-card--featured {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
}

.news-card h4 {
  margin: 0 0 10px 0;
  font-size: 18px;
  font-weight: 600;
  color: inherit;
}

.news-date {
  margin: 0;
  font-size: 14px;
  opacity: 0.8;
}

.news-list-block__loading,
.news-list-block__error,
.news-list-block__empty {
  padding: 40px;
  text-align: center;
  font-size: 16px;
}

.news-list-block__error {
  color: #e74c3c;
}

.news-list-block__empty {
  opacity: 0.6;
}

@media (max-width: 768px) {
  .news-list-block__grid {
    grid-template-columns: 1fr !important;
  }
}
</style>
